### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by ksendra** [idanwe/accounts-base-client-side#1]
This package is not working anymore (with newest versions of Meteor and Angular-Meteor) - https://github.com/Urigo/angular-meteor/issues/1349

Could you help us with this?
Thanks

**Comment by idanwe** [comment]
@ntoka Thanks for the notice.

I update the bundles and now it is fixed. 

I matched the version with the origin versioning (same as in meteor-client-side)
So, I released v1.2.8 with the matching idanwe/accounts-password-client-side#v1.1.11
